# Generated by Django 2.2 on 2019-11-24 20:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add_time')),
                ('titile', models.CharField(max_length=100, verbose_name='标题')),
                ('image', models.ImageField(max_length=500, upload_to='banner/%Y/%m', verbose_name='轮播图')),
                ('url', models.URLField(max_length=500, verbose_name='跳转链接')),
                ('index', models.IntegerField(default=0, verbose_name='顺序')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
