# Generated by Django 2.2 on 2019-11-24 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_banner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='titile',
            new_name='title',
        ),
    ]
