# Generated by Django 2.2 on 2019-11-02 13:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add_time')),
                ('name', models.CharField(max_length=50, verbose_name='course_name')),
                ('describe', models.CharField(max_length=300, verbose_name='description of courses')),
                ('learn_time', models.IntegerField(default=0, verbose_name='learn_time(minute)')),
                ('degree', models.CharField(choices=[('cj', 'easy'), ('zj', 'medium'), ('gj', 'difficult')], max_length=9)),
                ('students', models.IntegerField(default=0, verbose_name='students number')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='favorite_number')),
                ('click_nums', models.IntegerField(default=0, verbose_name='click times')),
                ('category', models.CharField(default='Backend', max_length=20, verbose_name='category')),
                ('tag', models.CharField(default='', max_length=10)),
                ('need_to_know', models.CharField(default='', max_length=300, verbose_name='Something you need to know')),
                ('teacher_tell', models.CharField(default='', max_length=300, verbose_name='teacher want to tell')),
                ('detail', models.TextField(default='', verbose_name='detail of course')),
                ('image', models.ImageField(upload_to='courses/%Y/%m', verbose_name='Cover image')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.Teacher', verbose_name='teacher')),
            ],
            options={
                'verbose_name': 'Courses information',
                'verbose_name_plural': 'Courses information',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add_time')),
                ('name', models.CharField(default='', max_length=10, verbose_name='Lesson_name')),
                ('learn_time', models.IntegerField(default=0, verbose_name='learn_time(minute)')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
            ],
            options={
                'verbose_name': 'course section',
                'verbose_name_plural': 'course section',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add_time')),
                ('name', models.CharField(default='', max_length=10, verbose_name='video_name')),
                ('learn_time', models.IntegerField(default=0, verbose_name='learn_time(minute)')),
                ('url', models.CharField(max_length=200, verbose_name='Video_url')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Lesson')),
            ],
            options={
                'verbose_name': 'Videos',
                'verbose_name_plural': 'Videos',
            },
        ),
        migrations.CreateModel(
            name='CourseResources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add_time')),
                ('name', models.CharField(default='', max_length=10, verbose_name='resource_name')),
                ('file', models.FileField(max_length=200, upload_to='course/resources/%Y/%m', verbose_name='file_address')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
            ],
            options={
                'verbose_name': 'course_resources',
                'verbose_name_plural': 'course_resources',
            },
        ),
    ]
