# Generated by Django 2.2 on 2019-11-13 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseresources',
            options={'verbose_name': 'Course Resources', 'verbose_name_plural': 'Course Resources'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'Lesson', 'verbose_name_plural': 'Lesson'},
        ),
    ]
