# Generated by Django 2.2 on 2019-11-20 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_coursetag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': '课程信息', 'verbose_name_plural': '课程信息'},
        ),
        migrations.AlterModelOptions(
            name='courseresources',
            options={'verbose_name': '课程资源', 'verbose_name_plural': '课程资源'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': '章节', 'verbose_name_plural': '章节'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': '视频', 'verbose_name_plural': '视频'},
        ),
        migrations.AddField(
            model_name='course',
            name='notice',
            field=models.CharField(default='', max_length=30, verbose_name='课程公告'),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(default='Backend', max_length=20, verbose_name='类别'),
        ),
        migrations.AlterField(
            model_name='course',
            name='click_nums',
            field=models.IntegerField(default=0, verbose_name='点击数'),
        ),
        migrations.AlterField(
            model_name='course',
            name='degree',
            field=models.CharField(choices=[('cj', '简单'), ('zj', '中等'), ('gj', '需要一定基础')], max_length=9, verbose_name='难度'),
        ),
        migrations.AlterField(
            model_name='course',
            name='describe',
            field=models.CharField(max_length=300, verbose_name='课程描述'),
        ),
        migrations.AlterField(
            model_name='course',
            name='detail',
            field=models.TextField(default='', verbose_name='课程详情'),
        ),
        migrations.AlterField(
            model_name='course',
            name='fav_nums',
            field=models.IntegerField(default=0, verbose_name='收藏数'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(upload_to='courses/%Y/%m', verbose_name='课程封面'),
        ),
        migrations.AlterField(
            model_name='course',
            name='learn_time',
            field=models.IntegerField(default=0, verbose_name='学习时长（分钟）'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=50, verbose_name='课程名字'),
        ),
        migrations.AlterField(
            model_name='course',
            name='need_to_know',
            field=models.CharField(default='', max_length=300, verbose_name='学前须知'),
        ),
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.IntegerField(default=0, verbose_name='学生数量'),
        ),
        migrations.AlterField(
            model_name='course',
            name='tag',
            field=models.CharField(default='', max_length=10, verbose_name='课程标签'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.Teacher', verbose_name='教师'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher_tell',
            field=models.CharField(default='', max_length=300, verbose_name='老师说'),
        ),
    ]
