# Generated by Django 2.2 on 2019-11-25 20:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_is_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='courseresources',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='courseresources',
            name='file',
            field=models.FileField(max_length=200, upload_to='course/resources/%Y/%m', verbose_name='资源url'),
        ),
        migrations.AlterField(
            model_name='courseresources',
            name='name',
            field=models.CharField(default='', max_length=10, verbose_name='资源名称'),
        ),
        migrations.AlterField(
            model_name='coursetag',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='learn_time',
            field=models.IntegerField(default=0, verbose_name='课程时长（分钟）'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='name',
            field=models.CharField(default='', max_length=10, verbose_name='课程名称'),
        ),
        migrations.AlterField(
            model_name='video',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='video',
            name='learn_time',
            field=models.IntegerField(default=0, verbose_name='视频时长（分钟）'),
        ),
        migrations.AlterField(
            model_name='video',
            name='name',
            field=models.CharField(default='', max_length=10, verbose_name='视频名称'),
        ),
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.CharField(max_length=1000, verbose_name='视频url'),
        ),
    ]
