# Generated by Django 2.2 on 2019-11-03 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191102_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mobile_phone',
            field=models.CharField(max_length=11, verbose_name='phone_number'),
        ),
    ]
