# Generated by Django 2.2 on 2019-11-02 13:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add_time')),
                ('name', models.CharField(max_length=20, verbose_name='city_name')),
                ('desc', models.CharField(max_length=200, verbose_name='description')),
            ],
            options={
                'verbose_name': 'city',
                'verbose_name_plural': 'city',
            },
        ),
        migrations.CreateModel(
            name='CourseOrg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add_time')),
                ('name', models.CharField(default='', max_length=10, verbose_name='organization_name')),
                ('desc', models.TextField(default='', verbose_name='description_of_organization')),
                ('tag', models.CharField(default='China Known', max_length=10, verbose_name='tag_of_organization')),
                ('category', models.CharField(choices=[('pxjg', 'training_organization'), ('gr', 'personal'), ('gx', 'school')], default='pxjg', max_length=24, verbose_name='category_of_organization')),
                ('click_nums', models.IntegerField(default=0, verbose_name='click_numbers')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='favourite_numbers')),
                ('image', models.ImageField(upload_to='org/%Y/%m', verbose_name='logo')),
                ('address', models.CharField(default='', max_length=150, verbose_name='address_of_org')),
                ('students', models.IntegerField(default=0, verbose_name='students_of_org')),
                ('course_nums', models.IntegerField(default=0, verbose_name='number_of_courses')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.City', verbose_name='city')),
            ],
            options={
                'verbose_name': 'organization',
                'verbose_name_plural': 'organization',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add_time')),
                ('name', models.CharField(default='', max_length=10, verbose_name='name_of_teacher')),
                ('work_years', models.IntegerField(default=0, verbose_name='work_years')),
                ('work_company', models.CharField(default='', max_length=50, verbose_name='work_company')),
                ('work_position', models.CharField(default='', max_length=10, verbose_name='work_position')),
                ('points', models.CharField(max_length=50, verbose_name='feature')),
                ('click_nums', models.IntegerField(default=0, verbose_name='click_numbers')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='favourite_numbers')),
                ('age', models.IntegerField(default=0, verbose_name='teacher_age')),
                ('image', models.ImageField(upload_to='teacher/%Y/%m', verbose_name='head_img')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.CourseOrg', verbose_name='organization')),
            ],
            options={
                'verbose_name': 'teacher',
                'verbose_name_plural': 'teacher',
            },
        ),
    ]
