# Generated by Django 2.2 on 2019-11-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_auto_20191114_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorg',
            name='tag',
            field=models.CharField(default='China Known', max_length=11, verbose_name='机构标签'),
        ),
    ]
